modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="icon@400.png"
authors="${mod_authors}"
description='''Gooey transfur mod inspired by Dragon Snow's Changed.'''
enumExtensions="META-INF/enumextensions.json"

[[mixins]]
config="changed.mixins.json"

[[mixins]]
config="changed.compatibility.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.changed]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.changed]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
